### ISSUE TITLE
character deletion bug

### ISSUE THREAD

**Issue by LatinScribe** [LatinScribe/UniversityExplorer#162]
If you delete a character, it get's added as the unicode '/b'

**Comment by LatinScribe** [comment]
We should probably just update the entire string isntead

**Comment by aclin05** [comment]
Where specifically is this found? Is this found in any of the search use cases?

**Comment by LatinScribe** [comment]
Not sure how much of an issue this could be elsewhere, but maybe in the profile creation, could be an issue as well, haven't tested yet

**Comment by aclin05** [comment]
This is definitely also an issue in the search use case, will give it a look

**Comment by LatinScribe** [comment]
If it's an issue, either just update the entire string through the action listener property update. Or, trim the string (probably even better since this fixes spaces) after the character gets added

**Comment by LatinScribe** [comment]
Double check if spaces are also an issue

**Comment by LatinScribe** [comment]
Fixed bugs on my end in #167
